### ISSUE TITLE
Cannot package an app with a scalable SVG icon

### ISSUE THREAD

**Issue by DuBistKomisch** [electron-userland/electron-installer-redhat#124]
**What version of `electron-installer-redhat` are you using?**

1.1.0

**What version of `node` and `npm` are you using?**

8.11.3, 6.6.0, yarn 1.13.0

**What operating system are you using?**

Ubuntu 17.10 and Arch Linux

**Can you compile the [example app](https://github.com/unindented/electron-installer-redhat/tree/master/example) successfully?**

yes

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-redhat.git
$ cd electron-installer-redhat/example
$ DEBUG='electron-installer-redhat' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-redhat`.**

`Makefile`:
```
	@npx electron-installer-redhat --src $(DIST_DIR)/vivi-linux-x64/ --dest $(DIST_DIR)/ --arch amd64 --config $(RES_DIR)/redhat.json
```

`res/redhat.json`:
```
{
  "icon": {
    "128x128": "res/icon_128.png",
    "scalable": "res/icon-v.svg"
  },
  "categories": ["Education", "Utility"],
  "requires": ["glib2", "pulseaudio-libs", "libX11"],
  "mimeType": ["x-scheme-handler/vivi"]
}
```

**What did you expect to happen?**

build to complete successfully like it did on 0.5.0

**What actually happened?**

```
Error: Error executing command (Exited with status 1):
rpmbuild -bb /tmp/electron-21346ql5fng9oWzf4/vivi_2.16.3_amd64/SPECS/vivi.spec --target amd64
+ umask 022
+ cd /tmp/electron-21346ql5fng9oWzf4/vivi_2.16.3_amd64/BUILD
+ mkdir -p /tmp/electron-21346ql5fng9oWzf4/vivi_2.16.3_amd64/BUILDROOT/vivi-2.16.3-1.x86_64/usr/
+ cp -r usr/bin usr/lib usr/share /tmp/electron-21346ql5fng9oWzf4/vivi_2.16.3_amd64/BUILDROOT/vivi-2.16.3-1.x86_64/usr/
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip /usr/bin/strip
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
error: File not found: /tmp/electron-21346ql5fng9oWzf4/vivi_2.16.3_amd64/BUILDROOT/vivi-2.16.3-1.x86_64/usr/share/icons/hicolor/scalable/apps/vivi.png
    File not found: /tmp/electron-21346ql5fng9oWzf4/vivi_2.16.3_amd64/BUILDROOT/vivi-2.16.3-1.x86_64/usr/share/icons/hicolor/scalable/apps/vivi.png
     
    at spawn.then.catch.err (/home/vividev/.buildkite-agent/builds/vivi-mini-ubuntu-linux/vivi/vivi-client/linux/node_modules/electron-installer-common/src/spawn.js:21:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) 'Error: Error executing command (Exited with status 1):\nrpmbuild -bb /tmp/electron-21346ql5fng9oWzf4/vivi_2.16.3_amd64/SPECS/vivi.spec --target amd64\n+ umask 022\n+ cd /tmp/electron-21346ql5fng9oWzf4/vivi_2.16.3_amd64/BUILD\n+ mkdir -p /tmp/electron-21346ql5fng9oWzf4/vivi_2.16.3_amd64/BUILDROOT/vivi-2.16.3-1.x86_64/usr/\n+ cp -r usr/bin usr/lib usr/share /tmp/electron-21346ql5fng9oWzf4/vivi_2.16.3_amd64/BUILDROOT/vivi-2.16.3-1.x86_64/usr/\n+ /usr/lib/rpm/brp-compress\n+ /usr/lib/rpm/brp-strip /usr/bin/strip\n+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip\n+ /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump\nerror: File not found: /tmp/electron-21346ql5fng9oWzf4/vivi_2.16.3_amd64/BUILDROOT/vivi-2.16.3-1.x86_64/usr/share/icons/hicolor/scalable/apps/vivi.png\n    File not found: /tmp/electron-21346ql5fng9oWzf4/vivi_2.16.3_amd64/BUILDROOT/vivi-2.16.3-1.x86_64/usr/share/icons/hicolor/scalable/apps/vivi.png\n\n    at spawn.then.catch.err (/home/vividev/.buildkite-agent/builds/vivi-mini-ubuntu-linux/vivi/vivi-client/linux/node_modules/electron-installer-common/src/spawn.js:21:13)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)'
```

doesn't seem to accept an svg, just looks for a png. just upgraded from 0.5.0 where this config was working, and electron-installer-debian handles the svg fine.

**Comment by malept** [comment]
I don't think SVGs ever worked? This is what the relevant version of the spec file template looked like in 0.5.0:

https://github.com/electron-userland/electron-installer-redhat/blob/a8d3fe61282ddeb452d1a65ae1ee17ba6e8c3deb/resources/spec.ejs#L26-L28

It's basically the same in master. At any rate, yeah, this is a bug.

**Comment by DuBistKomisch** [comment]
Looks like it used to "work" by renaming the file to .png, just extracted an older build:

```
 $ file usr/share/icons/hicolor/scalable/apps/vivi.png
usr/share/icons/hicolor/scalable/apps/vivi.png: SVG Scalable Vector Graphics image
```

**Comment by DuBistKomisch** [comment]
Would it be possible to get a release with this? I notice there's a bunch of refactoring sitting on master though, might need to wait for 1.2.0?

**Comment by fcastilloec** [comment]
There are some other PRs waiting for a review before a new release. The next one will be v2.0.0 due to some breaking changes

**Comment by DuBistKomisch** [comment]
Alright no worries, thanks.
