### ISSUE TITLE
Error while creating package on Fedora 41: cp: cannot stat 'usr/*': No such file or directory

### ISSUE THREAD

**Issue by anechunaev** [electron-userland/electron-installer-redhat#343]
**What version of `electron-installer-redhat` are you using?**
3.4.0

**What version of `node` and `npm` are you using?**
node v22.11.0 
npm v10.9.0

**What operating system are you using?**
Fedora 41

**Can you compile the [example app](https://github.com/electron-userland/electron-installer-redhat/tree/main/example) successfully?**
No

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/electron-userland/electron-installer-redhat.git
$ cd electron-installer-redhat/example
$ DEBUG='electron-installer-redhat' npm run build
```

<details>

<summary>Output</summary>

```
> example-electron-app@0.0.1 build
> npm run clean && npm run bundle:x64 && npm run rpm:x64


> example-electron-app@0.0.1 clean
> rimraf dist


> example-electron-app@0.0.1 bundle:x64
> electron-packager . --platform linux --arch x64 --out dist/

(node:149086) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Downloading tmp-149086-1-SHASUMS256.txt-9.4.4
[============================================>] 100.0% of 6 kB (6 kB/s)
Packaging app for platform linux x64 using electron v9.4.4
Wrote new app to dist/example-electron-app-linux-x64

> example-electron-app@0.0.1 rpm:x64
> electron-installer-redhat --src dist/example-electron-app-linux-x64/ --arch x86_64 --config config.json

Creating package (this may take a while)
electron-installer-redhat Executing command rpmbuild --version +0ms
electron-installer-redhat Reading package metadata from dist/example-electron-app-linux-x64/resources/app/package.json +7ms
electron-installer-redhat Creating package with options
electron-installer-redhat {
electron-installer-redhat   "src": "dist/example-electron-app-linux-x64/",
electron-installer-redhat   "arch": "x86_64",
electron-installer-redhat   "config": "config.json",
electron-installer-redhat   "dest": "dist/installers/",
electron-installer-redhat   "icon": "resources/Icon.png",
electron-installer-redhat   "categories": [
electron-installer-redhat     "Utility"
electron-installer-redhat   ],
electron-installer-redhat   "bin": "example-electron-app",
electron-installer-redhat   "execArguments": [],
electron-installer-redhat   "description": "An example app, built with Electron",
electron-installer-redhat   "genericName": "example-electron-app",
electron-installer-redhat   "homepage": "http://unindented.org/",
electron-installer-redhat   "mimeType": [],
electron-installer-redhat   "name": "example-electron-app",
electron-installer-redhat   "productDescription": "An example app, built with Electron.",
electron-installer-redhat   "productName": "example-electron-app",
electron-installer-redhat   "revision": 1,
electron-installer-redhat   "version": "0.0.1",
electron-installer-redhat   "license": "MIT",
electron-installer-redhat   "compressionLevel": 2,
electron-installer-redhat   "requires": [
electron-installer-redhat     "gtk3",
electron-installer-redhat     "(libnotify or libnotify4)",
electron-installer-redhat     "(nss or mozilla-nss)",
electron-installer-redhat     "(libXtst or libXtst6)",
electron-installer-redhat     "xdg-utils",
electron-installer-redhat     "at-spi2-core",
electron-installer-redhat     "libdrm",
electron-installer-redhat     "(mesa-libgbm or libgbm1)",
electron-installer-redhat     "(libxcb or libxcb1)",
electron-installer-redhat     "libXScrnSaver",
electron-installer-redhat     "(kde-cli-tools or kde-cli-tools5 or kde-runtime or trash-cli or glib2 or gvfs-client)"
electron-installer-redhat   ],
electron-installer-redhat   "vendor": "none",
electron-installer-redhat   "platform": "linux"
electron-installer-redhat } +2ms
electron-installer-redhat Creating spec file at /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/SPECS/example-electron-app.spec +1ms
electron-installer-redhat Creating package at /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64 +98ms
electron-installer-redhat Executing command rpmbuild -bb /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/SPECS/example-electron-app.spec --target x86_64-none-linux --define _topdir /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64 +1ms
ExitCodeError: Command failed with a non-zero return code (1):
rpmbuild -bb /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/SPECS/example-electron-app.spec --target x86_64-none-linux --define _topdir /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64
Executing(%mkbuilddir): /bin/sh -e /var/tmp/rpm-tmp.TIbrT8
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.p0rr8C

RPM build warnings:

RPM build errors:

Building target platforms: x86_64-none-linux
Building for target x86_64-none-linux
warning: %source_date_epoch_from_changelog is set, but %changelog has no entries to take a date from
+ umask 022
+ cd /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build
+ test -d /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build
+ /usr/bin/rm -rf /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build
+ /usr/bin/mkdir -p /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build
+ /usr/bin/mkdir -p /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/SPECPARTS
+ RPM_EC=0
++ jobs -p
+ exit 0
+ umask 022
+ cd /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build
+ '[' /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT '!=' / ']'
+ rm -rf /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT
++ dirname /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT
+ mkdir -p /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build
+ mkdir /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT
+ CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
+ export CFLAGS
+ CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
+ export CXXFLAGS
+ FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/lib64/gfortran/modules '
+ export FFLAGS
+ FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/lib64/gfortran/modules '
+ export FCFLAGS
+ VALAFLAGS=-g
+ export VALAFLAGS
+ RUSTFLAGS='-Copt-level=3 -Cdebuginfo=2 -Ccodegen-units=1 -Cstrip=none -Cforce-frame-pointers=yes -Clink-arg=-specs=/usr/lib/rpm/redhat/redhat-package-notes --cap-lints=warn'
+ export RUSTFLAGS
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes '
+ export LDFLAGS
+ LT_SYS_LIBRARY_PATH=/usr/lib64:
+ export LT_SYS_LIBRARY_PATH
+ CC=gcc
+ export CC
+ CXX=g++
+ export CXX
+ mkdir -p /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT/usr/
+ cp -r 'usr/*' /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT/usr/
cp: cannot stat 'usr/*': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.p0rr8C (%install)
%source_date_epoch_from_changelog is set, but %changelog has no entries to take a date from
Bad exit status from /var/tmp/rpm-tmp.p0rr8C (%install)
at ChildProcess.<anonymous> (/home/an/dev/electron-installer-redhat/example/node_modules/@malept/cross-spawn-promise/dist/src/index.js:99:24)
at ChildProcess.emit (node:events:518:28)
at maybeClose (node:internal/child_process:1104:16)
at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
cmd: 'rpmbuild',
args: [
'-bb',
'/tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/SPECS/example-electron-app.spec',
'--target',
'x86_64-none-linux',
'--define',
'_topdir /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64'
],
stdout: 'Executing(%mkbuilddir): /bin/sh -e /var/tmp/rpm-tmp.TIbrT8\n' +
'Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.p0rr8C\n' +
'\n' +
'RPM build warnings:\n' +
'\n' +
'RPM build errors:\n',
stderr: 'Building target platforms: x86_64-none-linux\n' +
'Building for target x86_64-none-linux\n' +
'warning: %source_date_epoch_from_changelog is set, but %changelog has no entries to take a date from\n' +
'+ umask 022\n' +
'+ cd /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build\n' +
'+ test -d /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build\n' +
'+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build\n' +
'+ /usr/bin/rm -rf /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build\n' +
'+ /usr/bin/mkdir -p /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build\n' +
'+ /usr/bin/mkdir -p /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/SPECPARTS\n' +
'+ RPM_EC=0\n' +
'++ jobs -p\n' +
'+ exit 0\n' +
'+ umask 022\n' +
'+ cd /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build\n' +
"+ '[' /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT '!=' / ']'\n" +
'+ rm -rf /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT\n' +
'++ dirname /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT\n' +
'+ mkdir -p /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build\n' +
'+ mkdir /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT\n' +
"+ CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '\n" +
'+ export CFLAGS\n' +
"+ CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '\n" +
'+ export CXXFLAGS\n' +
"+ FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/lib64/gfortran/modules '\n" +
'+ export FFLAGS\n' +
"+ FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/lib64/gfortran/modules '\n" +
'+ export FCFLAGS\n' +
'+ VALAFLAGS=-g\n' +
'+ export VALAFLAGS\n' +
"+ RUSTFLAGS='-Copt-level=3 -Cdebuginfo=2 -Ccodegen-units=1 -Cstrip=none -Cforce-frame-pointers=yes -Clink-arg=-specs=/usr/lib/rpm/redhat/redhat-package-notes --cap-lints=warn'\n" +
'+ export RUSTFLAGS\n' +
"+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes '\n" +
'+ export LDFLAGS\n' +
'+ LT_SYS_LIBRARY_PATH=/usr/lib64:\n' +
'+ export LT_SYS_LIBRARY_PATH\n' +
'+ CC=gcc\n' +
'+ export CC\n' +
'+ CXX=g++\n' +
'+ export CXX\n' +
'+ mkdir -p /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT/usr/\n' +
"+ cp -r 'usr/*' /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT/usr/\n" +
"cp: cannot stat 'usr/*': No such file or directory\n" +
'error: Bad exit status from /var/tmp/rpm-tmp.p0rr8C (%install)\n' +
'    %source_date_epoch_from_changelog is set, but %changelog has no entries to take a date from\n' +
'    Bad exit status from /var/tmp/rpm-tmp.p0rr8C (%install)\n',
code: 1
} Error: Command failed with a non-zero return code (1):
rpmbuild -bb /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/SPECS/example-electron-app.spec --target x86_64-none-linux --define _topdir /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64
Executing(%mkbuilddir): /bin/sh -e /var/tmp/rpm-tmp.TIbrT8
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.p0rr8C

RPM build warnings:

RPM build errors:

Building target platforms: x86_64-none-linux
Building for target x86_64-none-linux
warning: %source_date_epoch_from_changelog is set, but %changelog has no entries to take a date from
+ umask 022
+ cd /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build
+ test -d /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build
+ /usr/bin/rm -rf /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build
+ /usr/bin/mkdir -p /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build
+ /usr/bin/mkdir -p /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/SPECPARTS
+ RPM_EC=0
++ jobs -p
+ exit 0
+ umask 022
+ cd /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build
+ '[' /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT '!=' / ']'
+ rm -rf /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT
++ dirname /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT
+ mkdir -p /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build
+ mkdir /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT
+ CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
+ export CFLAGS
+ CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
+ export CXXFLAGS
+ FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/lib64/gfortran/modules '
+ export FFLAGS
+ FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/lib64/gfortran/modules '
+ export FCFLAGS
+ VALAFLAGS=-g
+ export VALAFLAGS
+ RUSTFLAGS='-Copt-level=3 -Cdebuginfo=2 -Ccodegen-units=1 -Cstrip=none -Cforce-frame-pointers=yes -Clink-arg=-specs=/usr/lib/rpm/redhat/redhat-package-notes --cap-lints=warn'
+ export RUSTFLAGS
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes '
+ export LDFLAGS
+ LT_SYS_LIBRARY_PATH=/usr/lib64:
+ export LT_SYS_LIBRARY_PATH
+ CC=gcc
+ export CC
+ CXX=g++
+ export CXX
+ mkdir -p /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT/usr/
+ cp -r 'usr/*' /tmp/electron-installer--149107-gtqlfWsrH16d/example-electron-app_0.0.1_x86_64/BUILD/example-electron-app-0.0.1-build/BUILDROOT/usr/
cp: cannot stat 'usr/*': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.p0rr8C (%install)
%source_date_epoch_from_changelog is set, but %changelog has no entries to take a date from
Bad exit status from /var/tmp/rpm-tmp.p0rr8C (%install)
at ChildProcess.<anonymous> (/home/an/dev/electron-installer-redhat/example/node_modules/@malept/cross-spawn-promise/dist/src/index.js:99:24)
at ChildProcess.emit (node:events:518:28)
at maybeClose (node:internal/child_process:1104:16)
at ChildProcess._handle.onexit (node:internal/child_process:304:5)  
```

</details>

**What did you do? Please include the configuration you are using for `electron-installer-redhat`.**

**What did you expect to happen?**
RPM package successfully built

**What actually happened?**
Error while building package

-----

The issue is also discussed here: https://github.com/electron/forge/issues/3701 It seems that it was caused by breaking changes in rpm: https://github.com/rpm-software-management/rpm/issues/2078

My temporary solution was to change this line:
https://github.com/electron-userland/electron-installer-redhat/blob/main/resources/spec.ejs#L27

```
- cp <%= process.platform === 'darwin' ? '-R' : '-r' %> usr/* %{buildroot}/usr/
+ cp <%= process.platform === 'darwin' ? '-R' : '-r' %> ../usr/. %{buildroot}/usr/
```

The proper solution probably should include some kind of external dependency handling and checking version of local rpm. But I don't know which versions you support, so no pull request :)

**Comment by werererer** [comment]
Would be great if this bug could be fixed: 

Got an issue dangling at trilium that has the same cause.
https://github.com/TriliumNext/Trilium/issues/6708

For me the issue happened for RPM >= 4.20.

**Comment by DerErzengel** [comment]
Still having the same issue.

**Comment by nerdCopter** [comment]
solved in https://github.com/electron-userland/electron-installer-redhat/pull/347 if they'll merge it.
